- alias: "Glasskab tænd"
  trigger:
  - platform: state
    entity_id: light.lampe_i_stuen
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.relay__button_3_1

- alias: "Glasskab sluk"
  trigger:
  - platform: state
    entity_id: light.lampe_i_stuen
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.relay__button_3_1
