- alias: alarm_action_auto_turnoff_on
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_tripped
    state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_enabled
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_config_action_auto_turnoff
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.alarm_auto_turn_off

- alias: alarm_action_auto_turnoff_off
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_tripped
    state: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_config_action_auto_turnoff
    state: 'on'
  action:
  - service: script.turn_off
    entity_id: script.alarm_auto_turn_off
