- alias: alarm_action_sound_sonos_on
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_tripped
    state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_enabled
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_config_action_noice
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.alarm_sound_sonos_start

- alias: alarm_action_sound_sonos_off
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_tripped
    state: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_config_action_noice
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.alarm_sound_sonos_stop
