save_input_settings: '/home/pi/.homeassistant/extraconfig/shell_scripts/hass_saved_settings.py -act update_settings -sec {{ section }} -set {{ settings }} -val "{{ value }}"'

load_input_settings: '/home/pi/.homeassistant/extraconfig/shell_scripts/hass_saved_settings.py -act update_hass -pw {{ password }}'
