- alias: livingroom_fuga1_knap1_on
  trigger:
  - platform: state
    entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_2
  condition:
   - condition: state
     entity_id: light.lampe_over_spisebord
     state: 'off'
  action:
    service: light.turn_on 
    entity_id: light.lampe_over_spisebord
    data:
      rgb_color: [255,202,122]
      brightness: 181
- alias: livingroom_fuga1_knap1_off
  trigger:
    - platform: state
      entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_2
  condition:
   - condition: state
     entity_id: light.lampe_over_spisebord
     state: 'on'
  action:
    service: light.turn_off
    entity_id: light.lampe_over_spisebord