- alias: livingroom_fuga1_knap1_off
  trigger:
    - platform: state
      entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_2
  condition:
  - condition: template
    value_template: >
      {{ 
          trigger.from_state.state != trigger.to_state.state 
          and is_state('light.lampe_over_spisebord','on')
          and (as_timestamp(now()) - as_timestamp(states.light.lampe_over_spisebord.last_updated) > 2)
      }}
  action:
    service: light.turn_off
    entity_id: light.lampe_over_spisebord

- alias: livingroom_fuga1_knap1_on
  trigger:
  - platform: state
    entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_2
  condition:
  - condition: template
    value_template: >
      {{ 
          trigger.from_state.state != trigger.to_state.state 
          and (
            is_state('light.lampe_over_spisebord','off')
            or
            is_state('light.lampe_over_spisebord','on')
            and (as_timestamp(now()) - as_timestamp(states.light.lampe_over_spisebord.last_updated) < 2)
            and states.light.lampe_over_spisebord.attributes.brightness == 81
          )
      }}
  action:
    service: light.turn_on 
    entity_id: light.lampe_over_spisebord
    data:
      rgb_color: [255,202,122]
      brightness: 181


- alias: livingroom_fuga1_knap1_on_funny_01
  trigger:
    - platform: state
      entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_2
  condition:
  - condition: template
    value_template: >
      {{ 
          trigger.from_state.state != trigger.to_state.state 
          and is_state('light.lampe_over_spisebord','on')
          and (as_timestamp(now()) - as_timestamp(states.light.lampe_over_spisebord.last_updated) < 2)
          and states.light.lampe_over_spisebord.attributes.brightness == 181         
      }}
  action:
    service: light.turn_on 
    entity_id: light.lampe_over_spisebord
    data:
      rgb_color: [243, 180, 80]
      brightness: 144
- alias: livingroom_fuga1_knap1_on_funny_02
  trigger:
    - platform: state
      entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_2
  condition:
  - condition: template
    value_template: >
      {{ 
          trigger.from_state.state != trigger.to_state.state 
          and is_state('light.lampe_over_spisebord','on')
          and (as_timestamp(now()) - as_timestamp(states.light.lampe_over_spisebord.last_updated) < 2)
          and states.light.lampe_over_spisebord.attributes.brightness == 144         
      }}
  action:
    service: light.turn_on 
    entity_id: light.lampe_over_spisebord
    data:
      rgb_color: [187,59,255]
      brightness: 81