- alias: livingroom_fuga1_knap4_on
  trigger:
  - platform: state
    entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_5
    from: 'off'
    to: 'on'
  action:
  - service: media_player.turn_off
    entity_id: media_player.lg_webos_smart_tv
  - service: shell_command.sonos_play_coffeehouse
  - service: shell_command.sonos_volume
    data:
      volume: 12

- alias: livingroom_fuga1_knap4_off
  trigger:
  - platform: state
    entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_5
    from: 'on'
    to: 'off'
  action:
  - service: shell_command.sonos_pause
