- alias: livingroom_fuga1_knap2_on
  trigger:
  - platform: state
    entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_3
  condition:
  - condition: state
    entity_id: light.lampe_i_stuen
    state: 'off'
  action:
  - service: light.turn_on 
    entity_id: light.lampe_i_stuen
    data:
      brightness: 254
  - service: switch.turn_on
    entity_id: switch.relay__button_3_1
  
- alias: livingroom_fuga1_knap2_off
  trigger:
  - platform: state
    entity_id: switch.logic_soft_zhc5010_wall_switch_switch_17_0_3
  condition:
  - condition: state
    entity_id: light.lampe_i_stuen
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.lampe_i_stuen
  - service: switch.turn_off
    entity_id: switch.relay__button_3_1


