- platform: template
  sensors:
    living_room_occupied:
      value_template: >
        {{ 
        is_state('media_player.lg_webos_smart_tv','playing')
        or is_state('sensor.aeotec_zw100_multisensor_6_burglar_2_10', '8')
        or (as_timestamp(now()) - as_timestamp(states.sensor.aeotec_zw100_multisensor_6_burglar_2_10.last_changed) < 60 * 5)
        or is_state('light.lampe_over_spisebord','on')
        }}
      friendly_name: 'Living room occupancy'
      device_class: occupancy
      entity_id: sensor.time
