- alias: Nattetiltand
  trigger:
  - platform: state
    entity_id: input_boolean.automation_climate_nightmode
  action:
   - service: climate.set_temperature
     data_template:
       entity_id: climate.danfoss_z_thermostat_014g0013_heating_1_3_1
       temperature: >
        {% if is_state('input_boolean.automation_climate_nightmode', 'on') %}
           {{ states('input_slider.climate_temperature_night') }}
         {% else %}
           {{ states('input_slider.climate_temperature_day') }}
         {% endif %}
   - service: notify.pushover
     data_template:
       message: >
         {% if is_state('input_boolean.automation_climate_nightmode', 'on') %}
           1Temperatur sat til {{ states('input_slider.climate_temperature_night') }}
         {% else %}
           1Temperatur sat til {{ states('input_slider.climate_temperature_day') }}
         {% endif %}

