 ## Save Input States to .ini - hass/saved_states
- alias: "Save Input States to Settings.ini"
  trigger:

  # Input booleans
   - platform: state
     entity_id: input_boolean.automation_disable_climate_nightmode
   - platform: state
     entity_id: input_boolean.automation_disable_exterior_lights

  #Input sliders
   - platform: state
     entity_id: input_slider.climate_temperature_day
   - platform: state
     entity_id: input_slider.climate_temperature_night

  #Input selects
   - platform: state
     entity_id: input_select.clima_nightmode_from
   - platform: state
     entity_id: input_select.clima_nightmode_to
  action:
    service: shell_command.save_input_settings
    data_template:
      section: '{{ trigger.entity_id }}'
      settings: '{{ trigger.entity_id }}'
      value: "{{ trigger.to_state.state }}"

##Load Input States from .ini - hass/saved_states

- alias: "Load Input States from Settings.ini"
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    - delay: 00:00:30
    - service: shell_command.load_input_settings
      data_template:
        key: !secret http_password