    
  automation_override:
    name: Automatiseringer 
    entities:
     - input_boolean.automation_disable_exterior_lights
     - input_boolean.automation_disable_climate_nightmode
     - input_boolean.automation_disable_door_notifications
     - input_boolean.automation_disable_linked_thermostats
     - input_boolean.automation_disable_scullary_lights

  alarm:
    name: Alarm
    entities:
     - input_boolean.alarm_enabled
     - input_boolean.alarm_tripped
     - input_boolean.alarm_config_action_noice
     - input_boolean.alarm_config_action_lights
     - input_boolean.alarm_config_action_auto_turnoff
     - input_boolean.alarm_config_location_on
     - input_boolean.alarm_config_location_off
     - input_boolean.alarm_config_trigger_movement
     - input_boolean.alarm_config_trigger_doors

  climate_nightmode:
    name: Nattetilstand for thermostater
    entities:
     - input_select.climate_nightmode_from
     - input_select.climate_nightmode_to
     - input_select.climate_nightmode_temperature
     - input_boolean.automation_climate_nightmode
     - input_select.climate_temperature_livingroom_day
     - input_select.climate_temperature_kitchen_day
     - input_select.climate_temperature_oliver_day
     - input_select.climate_temperature_hallway_day
     - input_select.climate_temperature_bathroom_day
     - input_select.climate_temperature_bedroom_day
     - input_select.climate_temperature_office_day  
