    
  automation_override:
    name: Automatiseringer 
    entities:
     - input_boolean.automation_disable_exterior_lights
     - input_boolean.automation_disable_climate_nightmode
     - input_boolean.automation_disable_door_notifications

  alarm:
    name: Alarm
    entities:
     - input_boolean.alarm_enabled
     - input_boolean.alarm_tripped
     - input_boolean.alarm_config_action_noice
     - input_boolean.alarm_config_action_lights
     - input_boolean.alarm_config_action_auto_turnoff
     - input_boolean.alarm_config_location_on
     - input_boolean.alarm_config_location_off
     - input_boolean.alarm_config_trigger_movement
     - input_boolean.alarm_config_trigger_doors

  climate_nightmode:
    name: Nattetilstand for thermostater
    entities:
     - input_select.clima_nightmode_from
     - input_select.clima_nightmode_to
     - input_boolean.automation_climate_nightmode
     - input_slider.climate_temperature_livingroom_day
     - input_slider.climate_temperature_livingroom_night
     - input_slider.climate_temperature_kitchen_day
     - input_slider.climate_temperature_kitchen_night
     - input_slider.climate_temperature_oliver_day
     - input_slider.climate_temperature_oliver_night
     - input_slider.climate_temperature_hallway_day
     - input_slider.climate_temperature_hallway_night
     - input_slider.climate_temperature_bathroom_day
     - input_slider.climate_temperature_bathroom_night
     - input_slider.climate_temperature_bedroom_day
     - input_slider.climate_temperature_bedroom_night
     - input_slider.climate_temperature_office_day  
     - input_slider.climate_temperature_office_night